# Generated by Django 3.0.5 on 2024-01-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='phone_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
