# Generated by Django 3.0.5 on 2024-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_bloodrequest_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
    ]
