# Generated by Django 3.0.5 on 2024-01-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_auto_20240129_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='unit',
            field=models.PositiveIntegerField(),
        ),
    ]
