# Generated by Django 3.0.5 on 2024-01-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='unit',
            field=models.PositiveIntegerField(),
        ),
    ]
